[package]
name = "markoff"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.16"
bevy_simple_subsecond_system = "0.2"
log = { version = "0.4", features = [
    "max_level_debug",
    "release_max_level_warn",
] }
tracing = { version = "0.1", features = [
    "max_level_debug",
    "release_max_level_warn",
] }
haalka = { git = "https://github.com/databasedav/haalka/", branch = "bevy_0.16" }
seldom_state = "0.14.0"

[features]
dev_native = []

### METADATA AND LINTS ########################################################
[package.metadata.bevy_cli.native.dev]
features = [
    # Enable asset hot reloading for native dev builds.
    "bevy/file_watcher",
    # Enable embedded asset hot reloading for native dev builds.
    "bevy/embedded_watcher",
]
[lints.clippy]
too_many_arguments = "allow"
type_complexity = "allow"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(bevy_lint)"] }

### BUILD OPTIMIZATION ########################################################
[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

# Remove expensive debug assertions due to <https://github.com/bevyengine/bevy/issues/14291>
[profile.dev.package.wgpu-types]
debug-assertions = false

[profile.release]
codegen-units = 1
lto = "thin"

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
